### ISSUE TITLE
Feature Request: Make STATUS of printers more "visible"

### ISSUE THREAD

**Issue by bolsoncerrado** [TFyre/bambu-farm#103]
Either (or both) making the background of the title cell or the STATUS cell to different colors (user selectable on settings?) depending on what's happening so we can have a quick look at the farm status when we have many printers to take care of.

A quick photoshop mockup of both options (I think both is more visual):

<img width="862" alt="mokcup" src="https://github.com/TFyre/bambu-farm/assets/10992914/3329f0d3-d727-4218-a296-a8a9d4bd8f15">

**Comment by TFyre** [comment]
heheheh my kinda design!! many other users would call it tooo colourful!

https://github.com/TFyre/bambu-farm/blob/main/bambu/src/main/java/com/tfyre/bambu/printer/BambuConst.java#L307

When I get a moment, I'll add the GCodeState to the html element so that you can use CSS to target it and set the colour.

**Comment by bolsoncerrado** [comment]
Awesome ;) If u can provide the sample CSS, twice awesome haha :P
